<!DOCTYPE html>
<html>
<head>
    <style>
        .receipt-box { max-width: 600px; margin: auto; padding: 30px; border: 1px solid #eee; font-family: 'Helvetica', sans-serif; }
        .header { text-align: center; color: #333; }
        .details { margin-top: 20px; width: 100%; border-collapse: collapse; }
        .details td { padding: 10px; border-bottom: 1px solid #f9f9f9; }
        .footer { margin-top: 30px; font-size: 12px; text-align: center; color: #888; }
        .amount { font-size: 24px; font-weight: bold; color: #2d3748; }
    </style>
</head>
<body>
    <div class="receipt-box">
        <div class="header">
            <h2>Oko-Irese Development Association (ODA)</h2>
            <p>Official eFund Receipt</p>
        </div>

        <p>Dear {{ $contribution->user->name }},</p>
        <p>Thank you for your contribution towards the development of our community. Below are your transaction details:</p>

        <table class="details">
            <tr>
                <td><strong>Transaction Ref:</strong></td>
                <td>{{ $contribution->transaction_reference }}</td>
            </tr>
            <tr>
                <td><strong>Date:</strong></td>
                <td>{{ $contribution->created_at->format('M d, Y H:i A') }}</td>
            </tr>
            <tr>
                <td><strong>Payment Purpose:</strong></td>
                <td>
                    @if($contribution->levy_id) {{ $contribution->levy->name }}
                    @elseif($contribution->campaign_id) {{ $contribution->campaign->title }}
                    @else Voluntary Donation @endif
                </td>
            </tr>
            <tr>
                <td><strong>Gateway:</strong></td>
                <td>{{ ucfirst($contribution->payment_gateway) }}</td>
            </tr>
            <tr>
                <td><strong>Amount Paid:</strong></td>
                <td class="amount">₦{{ number_format($contribution->amount, 2) }}</td>
            </tr>
        </table>

        <div class="footer">
            <p>This is an automated receipt generated by the ODA eFund Platform.</p>
            <p>Transparency & Accountability for Community Growth.</p>
        </div>
    </div>
</body>
</html>